[build]
base = "component/web-app"
command = "npm start build"
functions = "dist/api"
ignore = "npm start show.ciChanges"
publish = "dist/browser-client"


[dev]
autolaunch = true
command = "npm start dev.browserClient"


[[redirects]]
force = true
from = "/_api/*"
status = 200
to = "/.netlify/functions/:splat"

[[redirects]]
force = false
from = "/*"
status = 200
to = "/index.html"
